Repository redhat-developer/developers.redhat.com, pull requests merged in 2019-12, with the labels that each got.

#3415 Fix footer nav breakpoint
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/footer.js
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/rhd/footer.js
Labels: Bug, JavaScript

#3426 Implement new nav twig and css for jump nav
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_jump-to-nav.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--on-page-navigation.html.twig
Labels: Bug, Sprint-12.02.19, UX

#3412 Update Alerts to new styles
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/docs/content/components/alerts.md
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/@rhd/dp-alert.ts
Labels: UX

#3440 fix sign up footer
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/footer/context/base/rhd_footer.toml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_footer.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/block/block--system-menu-block--rhd-footer.html.twig
Labels: Sprint-12.09.19

#3441 [RHDX-64] Error: Call to a member function isPublished() on null
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/OnPageNavigationBuild.php
Labels: UX

#3350 [DEVELOPER 3307] Move inline scripts to libraries
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/js/custom-events.js
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/js/new-relic.min.js
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.info.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
Labels: Drupal

#3447 [RHDX-102] Multiple twig render array warnings
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/BonusContentItemBuild.php
Labels: UX

#3448 [RHDX-93] Update 'More like this' section to use new styles
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.product_related.inc
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/js/related-content.js
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/2018/related-content.js
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--video-resource--full.html.twig
Labels: UX
