Repository redhat-developer/developers.redhat.com, pull requests merged in 2020-03, with the labels that each got.

#3518 [RHDX-286] Split out patternfly imports / update base component styles
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-import.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_visual-styles.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--content-with-image.html.twig
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text-columns.html.twig
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text.html.twig
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--katacoda-course.html.twig
Labels: Ready for Review

#3521 [RHDX-162] Overflow x issue on code blocks
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_code-snippet.scss
Labels: UX

#3524 [RHDX-333] Make DownloadManagerApi use EntityTypeManagerInterface
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/DownloadManagerApi.php
Labels: Drupal

#3525 [RHDX-341] Add meta description to assembly_page content type
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.assembly_page.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_short_description.yml
  _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__assembly_page.yml
Labels: UX

#3519 [RHDX-302] Removed what is not used of PFE
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/package.json
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/2019/_background.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/2019/_link-type.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_mixins.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-base-variable-overrides.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/colors/_base.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/colors/_rhd-brand.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_assembly-base.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_buttons.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_dynamic-list.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rh-header.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/typography/_typography.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
Labels: Ready for Review

#3526 [RHDX-343] Patternfly source map not accurate in debugging
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/package.json
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
Labels: Ready for Review

#3515 [RHDX-250] Adobe DDO Taxonomy
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/html.html.twig
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
  _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
  _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
  _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
Labels: Ready for Review

#3534 [RHDX-350] Remove ckeditor stylesheet reference
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.info.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.info.yml
Labels: Ready for Review
