Repository redhat-developer/developers.redhat.com, pull requests merged in 2020-02, with the labels that each got.

#3499 [RHDX-246] Update display of multiple authors and guest authors
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_author.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/pages/_article.scss
Labels: UX

#3508 [RHDX-287] Update product listing view styles / classes
  _docker/drupal/drupal-filesystem/web/config/sync/views.view.all_products.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/2018/assembly/_all-products-listing.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_all-products-listing.scss
Labels: CSS, UX

#3511 [RHDX-296] Feature/card labels are overpass and not the correct color
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss
Labels: CSS, UX

#3496 [RHDX-221] Add webinar countdown component
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.call_to_action.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.call_to_action.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_display_cta_timer.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_display_cta_timer_label.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_display_cta_timer.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_display_cta_timer_label.yml
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/js/countdown.js
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.libraries.yml
  _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_assembly-base.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_call-to-action.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_card-grid.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_countdown.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cta-form.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_curated-events.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_events-hero.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rich-text-columns.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rich-text.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_visual-styles.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/typography/_dark.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--call-to-action.html.twig
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/field/field--assembly--field-display-cta-timer.html.twig
Labels: Ready for Review, UX

#3514 [RHDX-309] Add Kiosk Mode option
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.assembly_page.default.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_kiosk_mode.yml
  _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_kiosk_mode.yml
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/pages/_katacoda.scss
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
  _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/page--kiosk-mode.html.twig
Labels: Ready for Review, UX
